### ISSUE TITLE
Text is cut off on screen

### ISSUE THREAD

**Issue by korbelz** [Gamer-Dad/warlordsredux.altis#1]
Just trying to figure out how to submit the fix, I'm a noob at submitting pull request but the file that needs to be changed is: 
warlordsredux.altis/Functions/subroutines/WL2_sub_purchaseMenuGetUIScale.sqf

change 0.7 to 0.5

**Comment by Gamer-Dad** [comment]
GETUIScale modifier from 1.45 to 1.01, fixed!
