### ISSUE TITLE
No CP given to enemy team when -%

### ISSUE THREAD

**Issue by Gamer-Dad** [Gamer-Dad/warlordsredux.altis#123]
As subject states, we need to confirm this is not an issue anymore.

**Comment by DJGummikuh** [comment]
when we tried with a low player count (3) the issue didn't appear to happen. This *might* only show when there are enough players online so that the actual teamsize difference is much lower than 50% :thinking:

**Comment by MrThomasM** [comment]
I realise why its happening im pretty sure im gonna check out later

**Comment by MrThomasM** [comment]
uploaded a safety check
