### ISSUE TITLE
sectors that should not be able to be capped being capped

### ISSUE THREAD

**Issue by hirudo-mortifer** [Gamer-Dad/warlordsredux.altis#139]
In some circumstances it seems to be possible to capture a sector after resetting sector voting (to a different sector) without ever haven captured the sector

Not quite certain how to reproduce, as of now only encountered rarely

**Comment by WeasleyWalls** [comment]
Here is a step to step how to do it
1: Select sector
2: Reset sector voting and select another sector
3: Drive UGVs into the previous selected sctor
