### ISSUE TITLE
Vehicles No Longer Spawn on Roads/Buildings...following towns are incompatible 

### ISSUE THREAD

**Issue by korbelz** [Gamer-Dad/warlordsredux.altis#15]
Removing roads as a valid spawn point prevents building clipping when tanks/vic spawn but leaves only flat open fields with at least 6 meters clearance from blacklisted objects as valid spawn points. A few towns on the map have limited or no valid spawn points with this change, once the system is out of valid spawn points its fail state is to spawn items directly at the center of the town..think Edessa where everything would spawn at the bridge and explode.

The following towns needed adjustment to have at least 3 valid spawn spots.(most ended up with WAY more) Spelling is off on a few of these towns and I don't remember size increase for a few. 
- Ghost hotel...Much bigger
- Oreo...65m X and Y
- Aberra(town near NW little airport)...125m X and Y?(took multiple tries to fix this one)
- Gatiola...50m?
- Edessa...needs to move west a bit away from the bridge and buildings
- Negades..50m?
- power plant...25m X and Y
- Neri...25m X and Y(?)
- Zaros...25m X and Y(?) 
- Ligma(sp?) Solar....Move about 30 meters to the SW to work with new sector naming it was too close to Kat(south of Paros). Increased one of the Axis by 30ish meters to keep same zone coverage(the solar tower)

an alternative solution to embiggening towns(possible CP inflation) is to move all the above towns to an open field that you deem safe then let the spawn system run in its failed mode(it will always spawn tanks very close to the center mark). I mostly skipped out on this approach because AOs like Ghost hotel, Aberra, Negade, and Neri completely change character if you move the center point away from town center. 

all related commits:
https://github.com/korbelz/WarlordsReduxMe.altis/commit/dfce4b9a6be12c23493697be01dcdc067a86f65c

https://github.com/korbelz/WarlordsReduxMe.altis/commit/cfe30d8c18da055f84e7e343dc03307d24b43019

https://github.com/korbelz/WarlordsReduxMe.altis/commit/c3b8fcb849caa5a5ca3a5e0b60a9af1ab0bbe1da

https://github.com/korbelz/WarlordsReduxMe.altis/commit/b53badfc5039714ef566e1d02e6d051cf1824107

**Comment by Gamer-Dad** [comment]
Thanks buddy I'll make those commits.
