### ISSUE TITLE
Spawn issue

### ISSUE THREAD

**Issue by proudCobolWriter** [Gamer-Dad/warlordsredux.altis#151]
**Describe the bug**
Running a Redux mission on a dedicated server causes the player to not teleport to base as shown below. Note that this issue doesn't happen on self-hosted servers.

**To Reproduce**
1. Create a vanilla dedicated server (on Linux)
2. Install the newest redux mission
3. See the issue

**Screenshots**
![image (10)](https://github.com/Gamer-Dad/warlordsredux.altis/assets/77924245/c8c57508-3e7c-43f4-8abd-bb224128e324)

**Logs**
[serverlog.zip](https://github.com/Gamer-Dad/warlordsredux.altis/files/12064280/serverlog.zip)
mission loading starts at line 665

**Comment by proudCobolWriter** [comment]
Update: the spawn issue seems to resolve itself when disconnecting and reconnecting to the server

**Comment by spooker0** [comment]
Seems like a timing problem at the start for the first player. 
Putting a quick sleep before line 45 in `Functions/server/setupNewWarlords.sqf` seems to solve it, but not sure what the actual issue is.
