### ISSUE TITLE
Need update!

### ISSUE THREAD

**Issue by ZERONIGT** [Gamer-Dad/warlordsredux.altis#180]
An immediate update is needed, the current version is not working very well.

**Comment by MrThomasM** [comment]
Wich version? What isnt working well?

**Comment by MrThomasM** [comment]
Gotta give us something to work with other then it isnt working very well...

**Comment by Gamer-Dad** [comment]
A more intelligible ticket is needed, closing.

**Comment by ZERONIGT** [comment]
Version 2.8.0
1. The reward for killing the player's equipment does not work
2. Drones work very strangely (they cannot be used after spawning for 1-3 minutes)
3. There is a bug when it is impossible to spawn Wipeout

**Comment by Gamer-Dad** [comment]
Please join our discord, these issues are known about.
