### ISSUE TITLE
How do I turn off CP issuance?

### ISSUE THREAD

**Issue by ZERONIGT** [Gamer-Dad/warlordsredux.altis#181]
![image](https://github.com/Gamer-Dad/warlordsredux.altis/assets/78171863/1d9d347f-7686-46fc-a8fd-52b9aba07ee9)
How can I disable the 10k CP feature?

**Comment by MrThomasM** [comment]
in: 'initClient.sqf'. All the way on the bottom remove this code:
if !(["(EU) #11", serverName] call BIS_fnc_inString) then {
	player addAction [
		"10K CP",
		{[player, "10K"] remoteExec ["BIS_fnc_WL2_handleClientRequest", 2];}
	];
};
and in: 'onPlayerRespawn.sqf'. The same code:
if !(["(EU) #11", serverName] call BIS_fnc_inString) then {
	player addAction [
		"10K CP",
		{[player, "10K"] remoteExec ["BIS_fnc_WL2_handleClientRequest", 2];}
	];
};

**Comment by MrThomasM** [comment]
https://github.com/Gamer-Dad/warlordsredux.altis/wiki/Disable-10K-CP
