### ISSUE TITLE
Team Balance using CP Adjustments

### ISSUE THREAD

**Issue by Gamer-Dad** [Gamer-Dad/warlordsredux.altis#55]
To combat player imbalance, we'll add CP / min to an imbalanced team and deduct CP from the stacked team. 

Players will have a notification under their CP per minute with a +/- and blue/red color indicating what their actual CP is due to imbalance.

The formula for doing all this can be visually demonstrated below. Essentially it's a ratio of blufor to opfor. So if blufor has 20 players and opfor has 10 players, Opfor's CP will be double and Blufor's CP will be halved. 
![image](https://user-images.githubusercontent.com/60905510/215883056-408ce0aa-4a82-48de-96de-e0b3db8dff24.png)

**Comment by MrThomasM** [comment]
uploaded the cp balance code

**Comment by Gamer-Dad** [comment]
Testing showed more work needed but close.

**Comment by Gamer-Dad** [comment]
Seems to be working
