### ISSUE TITLE
Dazzler enabled via action menu for Tigris / Cheetah

### ISSUE THREAD

**Issue by Gamer-Dad** [Gamer-Dad/warlordsredux.altis#56]
The dazzler system confuses incoming guided missiles and causes them to miss. This system will be applied to the cheetahs/tigris.

For it to work, the player has to be manning it and manually turn it on via scroll wheel. This will provide decent protection against guided rounds. 

Rockets, GBUs, dumb rounds can still take out cheetahs/tigris.

The tigris/cheetah will be unable to fire outgoing AA when dazzler is on, otherwise their missiles will miss. Meaning they have to turn it off to fire their missiles. 

Once this is implemented we may look into introducing it for the kajman, blackfish armed, and possibly the xian (Drongo has a different system but works similar).

**Comment by MrThomasM** [comment]
Uploading it now

**Comment by Gamer-Dad** [comment]
Works but a few bugs to fix.
