### ISSUE TITLE
HEMMT Flatbed on OPFOR Recognized as BLUFOR Asset

### ISSUE THREAD

**Issue by Gamer-Dad** [Gamer-Dad/warlordsredux.altis#74]
Need to flag it as OPFOR on creation

**Comment by MrThomasM** [comment]
not sure if this is fixable well have to get more experience from tests

**Comment by Gamer-Dad** [comment]
This one might not be fixable.

**Comment by MrThomasM** [comment]
id close this. if i find some info on this issue ill repopen and check it out
