### ISSUE TITLE
Dazzler Enhanced for Device Truck

### ISSUE THREAD

**Issue by Gamer-Dad** [Gamer-Dad/warlordsredux.altis#78]
-Add APS back to Tigris and Cheetah

-Remove add action to Tigris and cheetah (save the script as we may use it for other vehicles in future)

-Add O_Truck_03_device_F to both OPFOR and BLUFOR requisitions, ensure blufor asset side is changed. 

-Add O_Truck_03_device_F to dazzler call in Drongos mod or copy dazzler script, rename to dazzler enhanced, and increase range of device to 300m.

-Add check for player/ai in drivers seat, engine on, not too high in altitude (sling load)

-Test

**Comment by MrThomasM** [comment]
To Do:
- engine needs to be on
- driver in vehicle

**Comment by MrThomasM** [comment]
fixed! ta da
